num_routers: 1
router_bias: true
max_epochs: ${training.epochs}
min_capacity: 0.5
max_capacity: 1.0
num_experts: 4
delta: 2.0
beta: 10.0
annealing_type: "linear"  # options: "linear", "cosine", "exponential"
