name: nested-vit-base
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4
qkv_bias: true
patch_size: 16
img_size: 224
num_classes: ${data.num_classes}

# Additional model parameters
num_routers: 1
ffn_type: ffn
router_type: epr