_target_: mone_pytorch.models.NestedVisionTransformer
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4
qkv_bias: true
patch_size: 16
img_size: 224
num_register_tokens: 0
num_classes: ${data.num_classes}

# Additional model parameters
num_routers: 1
capacity_distribution: null