_target_: mone_pytorch.models.nested_vit
embed_dim: 2048
depth: 48
num_heads: 32
mlp_ratio: 4
qkv_bias: true
patch_size: 16
img_size: 224
num_classes: ${data.num_classes}

# Additional model parameters
num_routers: 1
router_type: epr
ffn_type: ffn