name: vit-large
embed_dim: 1024
depth: 24
num_heads: 16
mlp_ratio: 4
qkv_bias: true
patch_size: 16
img_size: 224
num_classes: ${data.num_classes}
mlp_type: mlp
block_type: sequential
num_routers: ${mone.num_experts}
num_experts: ${mone.num_experts}
router_bias: ${mone.router_bias}
