name: nested-vit-small
embed_dim: 384
depth: 12
num_heads: 6
mlp_ratio: 4
qkv_bias: true
patch_size: 16
img_size: 224
num_classes: ${data.num_classes}

# Additional model parameters
num_routers: 1
use_alpha: false
mlp_type: mlp
block_type: sequential
shared_router: false