name: vit-small
embed_dim: 384
depth: 12
num_heads: 6
mlp_ratio: 4
qkv_bias: true
patch_size: 16
img_size: 224
num_classes: ${data.num_classes}
mlp_type: mlp
block_type: sequential
num_routers: ${mone.num_experts}
num_experts: ${mone.num_experts}
router_bias: ${mone.router_bias}
