defaults:
  - mone: null
  - model: base
  - optimizer: adamw
  - data: imagenet1k
  - augmentation: default
  - training: default
  - loggers:
    - csv_logger
    - wandb
  - scheduler: default
  - _self_

seed: 42
experiment_name: "default"
save_dir: "experiments"